//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazy.Vinke.Json.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LazyResourcesJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LazyResourcesJson() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazy.Vinke.Json.Properties.LazyResourcesJson", typeof(LazyResourcesJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End (*/).
        /// </summary>
        public static string LazyJsonCaptionCommentsInBlockEnd {
            get {
                return ResourceManager.GetString("LazyJsonCaptionCommentsInBlockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InLine (/) | InBlock (*).
        /// </summary>
        public static string LazyJsonCaptionCommentsInLineOrInBlock {
            get {
                return ResourceManager.GetString("LazyJsonCaptionCommentsInLineOrInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Array | Object | String | Integer | Decimal | Boolean | Null.
        /// </summary>
        public static string LazyJsonCaptionTokenType {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next (,) | End (]).
        /// </summary>
        public static string LazyJsonCaptionTokenTypeArrayNextOrEnd {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeArrayNextOrEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Integer | Decimal.
        /// </summary>
        public static string LazyJsonCaptionTokenTypeIntegerOrDecimal {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeIntegerOrDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boolean | Null.
        /// </summary>
        public static string LazyJsonCaptionTokenTypeNullOrBoolean {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeNullOrBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next (,) | End (}).
        /// </summary>
        public static string LazyJsonCaptionTokenTypeObjectNextOrEnd {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeObjectNextOrEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property (&quot;).
        /// </summary>
        public static string LazyJsonCaptionTokenTypeObjectProperty {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeObjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PropertyValue (:).
        /// </summary>
        public static string LazyJsonCaptionTokenTypeObjectPropertyValue {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeObjectPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End (&quot;).
        /// </summary>
        public static string LazyJsonCaptionTokenTypeStringEnd {
            get {
                return ResourceManager.GetString("LazyJsonCaptionTokenTypeStringEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LazyJsonReaderException (line {0} column {1}): Decimal token is missing decimal places!.
        /// </summary>
        public static string LazyJsonReaderExceptionTokenDecimalMissingDecimalPlaces {
            get {
                return ResourceManager.GetString("LazyJsonReaderExceptionTokenDecimalMissingDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LazyJsonReaderException (line {0} column {1}): Property ({2}) already exists on the object!.
        /// </summary>
        public static string LazyJsonReaderExceptionTokenObjectPropertyAlreadyExists {
            get {
                return ResourceManager.GetString("LazyJsonReaderExceptionTokenObjectPropertyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LazyJsonReaderException (line {0} column {1}): Unexpected character on the json! Expected ({2}) but got ({3})!.
        /// </summary>
        public static string LazyJsonReaderExceptionUnexpectedCharacter {
            get {
                return ResourceManager.GetString("LazyJsonReaderExceptionUnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LazyJsonReaderException (line {0} column {1}): Unexpected end of the json! Expected ({2}) but got ({3})!.
        /// </summary>
        public static string LazyJsonReaderExceptionUnexpectedEnd {
            get {
                return ResourceManager.GetString("LazyJsonReaderExceptionUnexpectedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LazyJsonReaderException (line {0} column {1}): Unexpected token on the json! Expected ({2}) but got ({3})!.
        /// </summary>
        public static string LazyJsonReaderExceptionUnexpectedToken {
            get {
                return ResourceManager.GetString("LazyJsonReaderExceptionUnexpectedToken", resourceCulture);
            }
        }
    }
}
