//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazy.Vinke.Database.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LazyResourcesDatabase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LazyResourcesDatabase() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazy.Vinke.Database.Properties.LazyResourcesDatabase", typeof(LazyResourcesDatabase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection is already close!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionAlreadyClose {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionAlreadyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection is already open!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection is not open!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionNotOpen {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection string cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The data row cannot be null!.
        /// </summary>
        public static string LazyDatabaseExceptionDataRowNull {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionDataRowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The fields array cannot be null or zero length!.
        /// </summary>
        public static string LazyDatabaseExceptionFieldsNullOrZeroLength {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionFieldsNullOrZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The query page data cannot be null!.
        /// </summary>
        public static string LazyDatabaseExceptionQueryPageDataNull {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionQueryPageDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The query page data &quot;order by&quot; cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionQueryPageDataOrderByNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionQueryPageDataOrderByNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The query page data &quot;page number&quot; must be higher than zero!.
        /// </summary>
        public static string LazyDatabaseExceptionQueryPageDataPageNumLowerThanOne {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionQueryPageDataPageNumLowerThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The query page data &quot;page size&quot; must be higher than zero!.
        /// </summary>
        public static string LazyDatabaseExceptionQueryPageDataPageSizeLowerThanOne {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionQueryPageDataPageSizeLowerThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The sql statement or procedure name cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionStatementNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionStatementNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The table name cannot contains white spaces!.
        /// </summary>
        public static string LazyDatabaseExceptionTableNameContainsWhiteSpace {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTableNameContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The table name cannot be null!.
        /// </summary>
        public static string LazyDatabaseExceptionTableNameNull {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTableNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The table name cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionTableNameNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTableNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database transaction is already open!.
        /// </summary>
        public static string LazyDatabaseExceptionTransactionAlreadyOpen {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTransactionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database transaction is not open!.
        /// </summary>
        public static string LazyDatabaseExceptionTransactionNotOpen {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTransactionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The types array cannot be null or zero length!.
        /// </summary>
        public static string LazyDatabaseExceptionTypesNullOrZeroLength {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTypesNullOrZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array cannot be null or zero length!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesNullOrZeroLength {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesNullOrZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array, the types array and the fields array must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesTypesFieldsNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesTypesFieldsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array, the types array and the parameters array must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesTypesParametersNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesTypesParametersNotMatch", resourceCulture);
            }
        }
    }
}
